export default {
  dark: {
    name: 'dark',
    primaryClr: '#e51b23',
    primaryTxtClr: '#ffffff',
    primaryBtnClr: '#000000',
    secondaryBtnClr: '#808286',
    primaryBtnBgClr: '#e51b23',
    secondaryBtnBgClr: '#EEF1F7',
    primaryIconClr: '#e51b23',
    secondaryIconClr: '#bfbfbf',
    primaryBgClr: '#000000',
    primaryCardBgClr: '#424242',
    primaryCardHClr: '#ffffff',
    primaryCardCClr: '#a2a2a2',
  },
  darkPlus: {
    name: 'darkPlus',
    primaryClr: '#e51b23',
    primaryTxtClr: '#ffffff',
    primaryBtnClr: '#000000',
    secondaryBtnClr: '#808286',
    primaryBtnBgClr: '#f2bb2b',
    secondaryBtnBgClr: '#EEF1F7',
    primaryIconClr: '#f2bb2b',
    secondaryIconClr: '#bfbfbf',
    primaryBgClr: '#000000',
    primaryCardBgClr: '#424242',
    primaryCardHClr: '#ffffff',
    primaryCardCClr: '#a2a2a2',
  },
  default: {
    name: 'default',
    primaryClr: '#e51b23', //red
    primaryColor2: '#f2bb2b', //yellow
    primaryColor3: '#414142', //grey
    primaryColor4: '#231f20', //black
    disabled: '#00000061',
    primaryTxtClr: '#ffffff',
    primaryBtnClr: '#ffffff',
    secondaryBtnClr: '#808286',
    primaryBtnBgClr: '#e51b23',
    secondaryBtnBgClr: '#EEF1F7',
    primaryIconClr: '#e51b23',
    secondaryIconClr: '#808080',
    primaryBgClr: '#ffffff',
    primaryCardBgClr: '#ffffff',
    primaryCardHClr: '#000000',
    primaryCardCClr: '#848484',
  },
};